use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end

target 'AZAPicker_Example' do
  pod 'AZAPicker', :path => '../'

  target 'AZAPicker_Tests' do
    inherit! :search_paths
  end
end
